export type ArrayApiCodeCategory = "negative" | "positive";

export const ARRAY_API_CODE_DEFINITIONS: Record<string, { category: ArrayApiCodeCategory; text: string }> = {
  "4": { category: "negative", text: "The balances on your accounts are too high compared to loan amounts" },
  "5": { category: "negative", text: "Too many of the delinquencies on your accounts are recent" },
  "6": { category: "negative", text: "You have too many accounts that were opened recently" },
  "7": { category: "negative", text: "You have too many delinquent or derogatory accounts" },
  "8": { category: "negative", text: "You have either very few loans or too many loans with recent delinquencies" },
  "9": { category: "negative", text: "The worst payment status on your accounts is delinquent or derogatory" },
  "10": { category: "negative", text: "You have either very few loans or too many loans with delinquencies" },
  "11": { category: "negative", text: "The total of your delinquent or derogatory account balances is too high" },
  "12": { category: "negative", text: "The date that you opened your oldest account is too recent" },
  "13": { category: "negative", text: "Your most recently opened account is too new" },
  "14": { category: "negative", text: "Lack of sufficient credit history" },
  "15": { category: "negative", text: "Newest delinquent or derogatory payment status on your accounts is too recent" },
  "16": { category: "negative", text: "The total of all balances on your open accounts is too high" },
  "17": { category: "negative", text: "Balances on previously delinquent accounts are too high compared to loan amts" },
  "18": { category: "negative", text: "Total of balances on accounts never late is too high compared to loan amounts" },
  "21": { category: "negative", text: "No open accounts in your credit file" },
  "22": { category: "negative", text: "No recently reported account information" },
  "23": { category: "negative", text: "Lack of sufficient relevant account information" },
  "29": { category: "negative", text: "Too many of your open bankcard or revolving accounts have a balance" },
  "30": { category: "negative", text: "Too few of your bankcard or other revolving accounts have high limits" },
  "31": { category: "negative", text: "Too many bankcard or other revolving accounts were opened recently" },
  "32": { category: "negative", text: "Balances on bankcard or revolving accounts too high compared to credit limits" },
  "33": { category: "negative", text: "Your worst bankcard or revolving account status is delinquent or derogatory" },
  "34": { category: "negative", text: "Total of all balances on bankcard or revolving accounts is too high" },
  "35": { category: "negative", text: "Your highest bankcard or revolving account balance is too high" },
  "36": { category: "negative", text: "Your largest credit limit on open bankcard or revolving accounts is too low" },
  "39": { category: "negative", text: "Available credit on your open bankcard or revolving accounts is too low" },
  "40": { category: "negative", text: "The date you opened your oldest bankcard or revolving account is too recent" },
  "42": { category: "negative", text: "The date you opened your newest bankcard or revolving account is too recent" },
  "43": { category: "negative", text: "Lack of sufficient credit history on bankcard or revolving accounts" },
  "44": { category: "negative", text: "Too many bankcard or revolving accounts with delinquent or derogatory status" },
  "45": { category: "negative", text: "Total balances too high on delinquent/derogatory bankcard or revolving accts" },
  "47": { category: "negative", text: "No open bankcard or revolving accounts in your credit file" },
  "48": { category: "negative", text: "No bankcard or revolving recently reported account information" },
  "49": { category: "negative", text: "Lack of sufficient relevant bankcard or revolving account information" },
  "53": { category: "negative", text: "The worst status on your real estate accounts is delinquent or derogatory" },
  "54": { category: "negative", text: "The amount of balance paid down on your open real estate accounts is too low" },
  "55": { category: "negative", text: "Open real estate account balances are too high compared to their loan amounts" },
  "57": { category: "negative", text: "Too many real estate accounts with delinquent or derogatory payment status" },
  "58": { category: "negative", text: "The total of all balances on your open real estate accounts is too high" },
  "61": { category: "negative", text: "No open real estate accounts in your credit file" },
  "62": { category: "negative", text: "No recently reported real estate account information" },
  "63": { category: "negative", text: "Lack of sufficient relevant real estate account information" },
  "64": { category: "negative", text: "No open first mortgage accounts in your credit file" },
  "65": { category: "negative", text: "Lack of sufficient relevant first mortgage account information" },
  "66": { category: "negative", text: "Your open auto account balances are too high compared to their loan amounts" },
  "68": { category: "negative", text: "No open auto accounts in your credit file" },
  "69": { category: "negative", text: "Lack of sufficient relevant auto account information" },
  "71": { category: "negative", text: "You have either very few installment loans or too many with delinquencies" },
  "72": { category: "negative", text: "Too many installment accounts with a delinquent or derogatory payment status" },
  "73": { category: "negative", text: "The worst status on your installment accounts is delinquent or derogatory" },
  "74": { category: "negative", text: "The balance amount paid down on your open installment accounts is too low" },
  "75": { category: "negative", text: "The installment account that you opened most recently is too new" },
  "76": { category: "negative", text: "You have insufficient credit history on installment loans" },
  "77": { category: "negative", text: "Newest delinquent or derogatory status on installment accounts is too recent" },
  "78": { category: "negative", text: "Balances on installment accounts are too high compared to their loan amounts" },
  "79": { category: "negative", text: "Too many of the delinquencies on your installment accounts are recent" },
  "81": { category: "negative", text: "No open installment accounts in your credit file" },
  "83": { category: "negative", text: "Lack of sufficient relevant installment account information" },
  "84": { category: "negative", text: "The number of inquiries was also a factor, but effect was not significant" },
  "85": { category: "negative", text: "You have too many inquiries on your credit report." },
  "86": { category: "negative", text: "Your credit report contains too many derogatory public records" },
  "87": { category: "negative", text: "Your credit report contains too many unsatisfied public records" },
  "88": { category: "negative", text: "One or more derogatory public records in your credit file is too recent" },
  "90": { category: "negative", text: "Too few discharged bankruptcies" },
  "93": { category: "negative", text: "The worst status on your student loan accounts is delinquent or derogatory" },
  "94": { category: "negative", text: "The balance amount paid down on your open student loan accounts is too low" },
  "95": { category: "negative", text: "You have too many collection agency accounts that are unpaid" },
  "96": { category: "negative", text: "The total you owe on collection agency accounts is high" },
  "97": { category: "negative", text: "You have too few credit accounts" },
  "98": { category: "negative", text: "There is a bankruptcy on your credit report" },
  "Y": { category: "negative", text: "Number of inquiries adversely affected the score but not significantly" },

  "P04": { category: "positive", text: "The balances on your accounts are not too high compared to loan limits" },
  "P05": { category: "positive", text: "There are no or only a few recent delinquencies on your accounts" },
  "P06": { category: "positive", text: "You have few or no accounts that were opened recently" },
  "P07": { category: "positive", text: "You have either no or few delinquent or derogatory accounts" },
  "P08": { category: "positive", text: "One or more of your accounts were paid on time in recent months" },
  "P09": { category: "positive", text: "None of your accounts have a severe delinquency or a derogatory status" },
  "P10": { category: "positive", text: "One or more of your accounts have been paid on time" },
  "P11": { category: "positive", text: "You have few or no accounts with delinquent or derogatory balances" },
  "P12": { category: "positive", text: "The date that you opened your oldest account is not too recent" },
  "P13": { category: "positive", text: "Your most recently opened account is not too new" },
  "P14": { category: "positive", text: "Your credit file contains enough information about your use of credit" },
  "P15": { category: "positive", text: "None of your accounts have a recent delinquency or a derogatory status" },
  "P16": { category: "positive", text: "The total of all balances on your open accounts is not too high" },
  "P17": { category: "positive", text: "Balances on prior delinquent accounts not too high compared to loan amts" },
  "P18": { category: "positive", text: "Total of balances on accts never late not too high compared to loan amts" },
  "P21": { category: "positive", text: "No open accounts in your credit file" },
  "P22": { category: "positive", text: "No recently reported account information" },
  "P23": { category: "positive", text: "Lack of sufficient relevant account information" },
  "P29": { category: "positive", text: "Few or none of your open bankcard or revolving accounts has a balance" },
  "P30": { category: "positive", text: "One or more of your bankcard or revolving accounts has a high limit" },
  "P31": { category: "positive", text: "Few or none of your bankcard or revolving accounts was opened recently" },
  "P32": { category: "positive", text: "Balances on bankcard or revolving accts not too high compared to limits" },
  "P33": { category: "positive", text: "No severe delinquency/derogatory status on bankcard or revolving accts" },
  "P34": { category: "positive", text: "Total of all balances on bankcard or revolving accounts is not too high" },
  "P35": { category: "positive", text: "Your highest bankcard or revolving account balance is not too high" },
  "P36": { category: "positive", text: "Largest credit limit on open bankcard or revolving accts is not too low" },
  "P39": { category: "positive", text: "Available credit on open bankcard or revolving accounts is not too low" },
  "P40": { category: "positive", text: "Date your oldest bankcard or revolving account opened is not too recent" },
  "P42": { category: "positive", text: "Date your newest bankcard or revolving account opened is not too recent" },
  "P43": { category: "positive", text: "Credit file has enough history on your use of bankcard/revolving accts" },
  "P44": { category: "positive", text: "Few or no bankcard or revolving accts with delinquent/derogatory status" },
  "P45": { category: "positive", text: "Few or no bankcard/revolving accts with delinquent/derogatory balances" },
  "P47": { category: "positive", text: "No open bankcard or revolving accounts in your credit file" },
  "P48": { category: "positive", text: "No bankcard or revolving recently reported account information" },
  "P49": { category: "positive", text: "Lack of sufficient relevant bankcard or revolving account information" },
  "P50": { category: "positive", text: "No open retail revolving accounts in your credit file" },
  "P52": { category: "positive", text: "No open home equity loans in your credit file" },
  "P53": { category: "positive", text: "No real estate accounts with severe delinquency or derogatory status" },
  "P54": { category: "positive", text: "Amount of balance paid down on open real estate accounts is not too low" },
  "P55": { category: "positive", text: "Open real estate account balances not too high compared to loan amounts" },
  "P57": { category: "positive", text: "Few or no real estate accts with delinquent or derogatory payment status" },
  "P58": { category: "positive", text: "The total of all balances on open real estate accounts is not too high" },
  "P61": { category: "positive", text: "No open real estate accounts in your credit file" },
  "P62": { category: "positive", text: "No recently reported real estate account information" },
  "P63": { category: "positive", text: "Lack of sufficient relevant real estate account information" },
  "P64": { category: "positive", text: "No open first mortgage accounts in your credit file" },
  "P65": { category: "positive", text: "Lack of sufficient relevant first mortgage account information" },
  "P66": { category: "positive", text: "Balances on open auto accounts are not too high compared to loan amounts" },
  "P68": { category: "positive", text: "No open auto accounts in your credit file" },
  "P69": { category: "positive", text: "Lack of sufficient relevant auto account information" },
  "P70": { category: "positive", text: "No open personal installment loans in your credit file" },
  "P71": { category: "positive", text: "One or more of your installment accounts has been paid on time" },
  "P72": { category: "positive", text: "Few or no installment accts with delinquent or derogatory payment status" },
  "P73": { category: "positive", text: "No installment accounts with a severe delinquency or derogatory status" },
  "P74": { category: "positive", text: "Amount of balance paid down on open installment accounts is not too low" },
  "P75": { category: "positive", text: "Your most recently opened installment account is not too new" },
  "P76": { category: "positive", text: "Your credit file has enough history on your use of installment loans" },
  "P77": { category: "positive", text: "Newest delinquent/derogatory status on installment accts not too recent" },
  "P78": { category: "positive", text: "Installment account balances not too high compared to loan amounts" },
  "P79": { category: "positive", text: "You have few or no recent delinquencies on your installment accounts" },
  "P81": { category: "positive", text: "No open installment accounts in your credit file" },
  "P83": { category: "positive", text: "Lack of sufficient relevant installment account information" },
  "P85": { category: "positive", text: "You have few or no inquiries on your credit report" },
  "P86": { category: "positive", text: "You have few or no derogatory public records on your credit report" },
  "P87": { category: "positive", text: "You have few or no unsatisfied public records on your credit report" },
  "P88": { category: "positive", text: "You have no recent derogatory public records on your credit report" },
  "P90": { category: "positive", text: "You have one or more discharged bankruptcies" },
  "P92": { category: "positive", text: "No open student loan accounts in your credit file" },
  "P93": { category: "positive", text: "No student loan accounts with a severe delinquency or derogatory status" },
  "P94": { category: "positive", text: "Amount of balance paid down on open student loan accounts is not too low" },
  "P95": { category: "positive", text: "You have few or no unpaid collection agency accounts" },
  "P96": { category: "positive", text: "You have few or no collection agency account balances" },
  "P98": { category: "positive", text: "There is no bankruptcy on your credit report" },
};

export function normalizeArrayApiCode(input: string): string {
  const raw = String(input ?? "").trim();
  if (!raw) return "";
  const upper = raw.toUpperCase();
  if (/^P\d{1,2}$/.test(upper)) {
    const num = upper.slice(1);
    return `P${num.padStart(2, "0")}`;
  }
  return upper;
}

export function getArrayApiCodeDefinition(code: string): { category: ArrayApiCodeCategory; text: string } | null {
  const normalized = normalizeArrayApiCode(code);
  return ARRAY_API_CODE_DEFINITIONS[normalized] ?? null;
}

export function isArrayApiCode(code: string): boolean {
  return Boolean(getArrayApiCodeDefinition(code));
}
