// app/api/array/user-token/route.ts
//
// NOTE: Array sandbox does not expose a separate secret API key.
// The userToken is generated by the <array-account-enroll> web component
// during enrollment and passed to /login via URL params.
//
// This route is kept as a placeholder for production use if Array
// provides a server-side token endpoint in the future.

import { NextResponse } from "next/server";

export async function POST() {
  return NextResponse.json(
    { error: "Not implemented. userToken is generated by the Array enroll component." },
    { status: 501 }
  );
}
